[/]
fixed-widths=true
hide-zeros=false
hot-sensors=['_memory_available_', '_memory_allocated_', '_processor_frequency_', '_processor_usage_', '__network-tx_max__', '__network-rx_max__', '__temperature_avg__', '_temperature_gpu_']
icon-style=1
include-static-gpu-info=true
menu-centered=true
position-in-panel=0
show-battery=true
show-gpu=true
show-storage=false
use-higher-precision=true
