[/]
settings-version=2

[appfolder]
brightness=0.59999999999999998
sigma=30

[applications]
blur=true
brightness=0.40000000000000002
dynamic-opacity=true
opacity=80
sigma=50
whitelist=['org.gnome.Nautilus', 'io.quantumencoding.baton']

[coverflow-alt-tab]
pipeline='pipeline_default'

[dash-to-dock]
blur=true
brightness=0.59999999999999998
pipeline='pipeline_default_rounded'
sigma=30
static-blur=true
style-dash-to-dock=0

[lockscreen]
pipeline='pipeline_default'

[overview]
blur=true
pipeline='pipeline_default'
sigma=30

[panel]
blur=true
brightness=0.59999999999999998
customize=true
pipeline='pipeline_default_rounded'
sigma=30
style-panel=2

[screenshot]
pipeline='pipeline_default'

[window-list]
brightness=0.59999999999999998
sigma=30
